services:

  # backend:
  #   build: .
  #   command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000

  frontend:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud